package me.ezra_home.retail_software_solution.locations.business.expense

import me.ezra_home.retail_software_solution.cross_tier.expense.repository.ExpensePaymentRepositoryBase
import org.springframework.stereotype.Repository

@Repository
interface ExpensePaymentRepository : ExpensePaymentRepositoryBase<ExpensePaymentEntity>
