databaseChangeLog:
  - changeSet:
      id: 'add-foreign-key-product-group-category'
      author: ezra
      labels: 1.0.0
      preConditions:
        - onFail: MARK_RAN
        - not:
            - foreignKeyConstraintExists:
                foreignKeyName: fk_product_group_category
      changes:
        - addForeignKeyConstraint:
            baseTableName: product_group
            baseColumnNames: category_id
            referencedTableName: category
            referencedColumnNames: id
            constraintName: fk_product_group_category
      rollback:
        - dropForeignKeyConstraint:
            baseTableName: product_group
            constraintName: fk_product_group_category
