databaseChangeLog:
  - changeSet:
      id: 'create-entry-for-product-group-in-table-registry'
      author: ezra
      changes:
        - insert:
            tableName: table_registry
            columns:
              - column:
                  name: id
                  valueComputed: ${uuid_function}
              - column:
                  name: table_name
                  value: product_group
              - column:
                  name: default_prefix
                  value: PGRP
              - column:
                  name: minimum_version_id
                  valueComputed: (SELECT id FROM db_version WHERE version_number = '1.0.0')
              - column:
                  name: schema_level
                  value: ORG
              - column:
                  name: display_name
                  value: Product Group
              - column:
                  name: description
                  value: Table containing product groups
              - column:
                  name: reference_number
                  value: PTBL21
