spring:
  application:
    name: retail-software-solution
  datasource:
    url: ''

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/${AUTH_SERVER}
    audience: ${AUDIENCE}

server:
  port: ${PORT:8080}
