spring:
  application:
    name: retail-software-solution

  datasource:
    location:
      jdbc-url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?sslmode=prefer
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      changelog: db/changelog/locations/db-changelog-master.yml
      hikari:
        auto-commit: false
        idle-timeout: 300000  # 5 minutes
        max-lifetime: 600000

    platform: # Datasource for metadata
      jdbc-url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?sslmode=prefer&currentSchema=platform
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
        auto-commit: false
        idle-timeout: 300000  # 5 minutes
        max-lifetime: 600000

    organization:
      jdbc-url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?sslmode=prefer
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      changelog: db/changelog/organizations/db-changelog-master.yml
      hikari:
        auto-commit: false
        idle-timeout: 300000  # 5 minutes
        max-lifetime: 600000

  cache:
    caffeine:
      spec: maximumSize=100

  jpa:
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    hibernate:
      ddl-auto: validate

  task:
    scheduling:
      pool:
        size: 5

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
  client:
    org-url: https://${OKTA_DOMAIN}
    token: ${OKTA_API_TOKEN}

server:
  port: ${PORT:8080}
  error:
    include-message: always

logging:
  level:
    org.hibernate:
      SQL: ${HIBERNATE_SQL_LOGGING:DEBUG}
      envers: ${HIBERNATE_ENVERS_LOGGING:DEBUG}
      type: ${HIBERNATE_TYPE_LOGGING:TRACE}
