spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rtss
    username: chumo
    password: pw
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yml
    enabled: true
    default-schema: public

okta:
  oauth2:
    issuer: https://dev-53842745.okta.com/oauth2/default  # Add /oauth2/default
    client-id: 0oalpixre116COtDC5d7
    client-secret: 4p_vRrU674E3Q4qAVoZHJoj0HqeZVQhTVucOBPu7FktpxUhBrZ4v_ogr4RNl0x6K
  client:
    org-url: https://dev-53842745.okta.com
    token: 00wrrOFzU9vLRFztyF1z4JWjLe4b2ynyA7jb0v2nVM

server:
  port: 8080
  error:
    include-message: always

spring.jmx.enabled: true