spring:
  application:
    name: retail-software-solution

  datasource:
    url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?stringtype=unspecified&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cache:
    caffeine:
      spec: maximumSize=100

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yml

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full
  jpa:
    show-sql: ${SHOW_SQL:false}

  task:
    scheduling:
      pool:
        size: 5

  jackson:
    time-zone: UTC

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/${AUTH_SERVER}
    audience: ${AUDIENCE}

server:
  port: ${PORT:8080}

