package me.ezra_home.retail_software_solution.util.enums

object RtsPermissionNames {
    const val ADD_USER_TO_LOCATION = "ADD_USER_TO_LOCATION"
    const val CREATE_ORGANIZATION = "CREATE_ORGANIZATION"
    const val MANAGE_LOCATION_ACCESS = "MANAGE_LOCATION_ACCESS"
    const val MANAGE_ORG_ACCESS = "MANAGE_ORG_ACCESS"
    const val REMOVE_USER_FROM_LOCATION = "REMOVE_USER_FROM_LOCATION"
    const val REMOVE_USER_FROM_ORG = "REMOVE_USER_FROM_ORG"
    const val VIEW_USERS_OF_LOCATION = "VIEW_USERS_OF_LOCATION"
    const val VIEW_USERS_OF_ORG = "VIEW_USERS_OF_ORG"
}
