databaseChangeLog:
  - changeSet:
      id: create-product-aud-table
      author: ezra
      labels: 1.0.0
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              tableName: product_aud
      changes:
        - createTable:
            tableName: product_aud
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: rev
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: revtype
                  type: smallint
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: nvarchar2(200)
              - column:
                  name: description
                  type: nvarchar2(1500)
              - column:
                  name: product_group_id
                  type: uuid
              - column:
                  name: base_unit_id
                  type: uuid
              - column:
                  name: status
                  type: nvarchar2(5)
              - column:
                  name: revend
                  type: bigint
              - column:
                  name: revend_tstmp
                  type: timestamp
        - addPrimaryKey:
            tableName: product_aud
            columnNames: id, rev
            constraintName: pk_product_aud
      rollback:
        - dropTable:
            tableName: product_aud
