databaseChangeLog:
  - changeSet:
      id: 'create-sequence-product-reference-number'
      author: ezra
      labels: 1.0.0
      changes:
        - createSequence:
            sequenceName: seq_product_reference_number
            startValue: 1
            incrementBy: 1
