package me.ezra_home.retail_software_solution.util.model

object TableNames {
    // Platform tables
    const val FEATURE = "feature"
    const val ORGANIZATION_FEATURE = "organization_feature"
    const val ORGANIZATION = "organization"
    const val ORGANIZATION_ADMIN = "organization_admin"
    const val RESERVED_SUBDOMAIN = "reserved_subdomain"
    const val ORGANIZATION_JOIN_REQUEST = "org_join_request"
    const val DB_VERSION = "db_version"
    const val DB_MIGRATION = "db_migration"
    const val TABLE_REGISTRY = "table_registry"
    const val AUTHORIZATION_PASS = "authorization_pass"
    const val JURISDICTION_TYPE = "jurisdiction_type"
    const val TAX_TYPE = "tax_type"
    const val JURISDICTION = "jurisdiction"
    const val JURISDICTION_TAX_TYPE = "jurisdiction_tax_type"
    const val SYS_USER = "sys_user"

    // Organization tables
    const val ACCOUNT = "account"
    const val ADDRESS = "address"
    const val CONTACT = "contact"
    const val LOCATION = "location"
    const val PRODUCT_CATEGORY = "product_category"
    const val JOB_TITLE = "job_title"
    const val UNIT_GROUP = "unit_group"
    const val UNIT_VALUE = "unit_value"
    const val PAYMENT_METHOD = "payment_method"
    const val ORGANIZATION_USER = "organization_user"
    const val PRODUCT = "product"
    const val PRODUCT_GROUP = "product_group"
    const val PRODUCT_TAG = "product_tag"
    const val ORG_TABLE_REGISTRY = "org_table_registry"
    const val TAG = "tag"
    const val STOCK_MOVEMENT_REASON = "stock_movement_reason"
    const val STOCK_MOVEMENT_REASON_TYPE = "stock_movement_reason_type"
    const val STOCK_ITEM_SOURCE = "stock_item_source"
    const val TAX_RATE = "tax_rate"
    const val PRODUCT_TAX_ASSIGNMENT = "product_tax_assignment"
    const val ORG_JURISDICTION_TAX_TYPE = "org_jurisdiction_tax_type"
    const val ORG_ACCOUNTING_CONFIG = "org_accounting_config"
    const val FISCAL_PERIOD = "fiscal_period"
    const val LEDGER_ENTRY_GROUP = "ledger_entry_group"
    const val LEDGER_ENTRY = "ledger_entry"
    const val SUBLEDGER_ENTRY = "subledger_entry"

    // Location tables
    const val EVENT_PROCESSING_LOG = "event_processing_log"
    const val SYNC_LOG = "sync_log"
    const val LOCATION_PRODUCT = "location_product"
    const val PURCHASE = "purchase"
    const val PURCHASE_LINE = "purchase_line"
    const val PURCHASE_DELIVERY = "purchase_delivery"
    const val PURCHASE_DELIVERY_LINE = "purchase_delivery_line"
    const val STOCK_ENTRY = "stock_entry"
    const val STOCK_MOVEMENT = "stock_movement"
    const val SUPPLIER_RETURN = "supplier_return"

    // Platform audit tables
    const val ORGANIZATION_AUDIT = "organization_aud"
    const val AUTHORIZATION_PASS_AUDIT = "authorization_pass_aud"
    const val JURISDICTION_TYPE_AUDIT = "jurisdiction_type_aud"
    const val TAX_TYPE_AUDIT = "tax_type_aud"
    const val JURISDICTION_AUDIT = "jurisdiction_aud"
    const val JURISDICTION_TAX_TYPE_AUDIT = "jurisdiction_tax_type_aud"

    // Organization audit tables
    const val ACCOUNT_AUDIT = "account_aud"
    const val ADDRESS_AUDIT = "address_aud"
    const val CONTACT_AUDIT = "contact_aud"
    const val JOB_TITLE_AUDIT = "job_title_aud"
    const val UNIT_GROUP_AUDIT = "unit_group_aud"
    const val UNIT_VALUE_AUDIT = "unit_value_aud"
    const val LOCATION_AUDIT = "location_aud"
    const val PAYMENT_METHOD_AUDIT = "payment_method_aud"
    const val TAG_AUDIT = "tag_aud"
    const val PRODUCT_AUDIT = "product_aud"
    const val PRODUCT_CATEGORY_AUDIT = "product_category_aud"
    const val PRODUCT_GROUP_AUDIT = "product_group_aud"
    const val TAX_RATE_AUDIT = "tax_rate_aud"
    const val PRODUCT_TAX_ASSIGNMENT_AUDIT = "product_tax_assignment_aud"
    const val ORG_JURISDICTION_TAX_TYPE_AUDIT = "org_jurisdiction_tax_type_aud"
    const val FISCAL_PERIOD_AUDIT = "fiscal_period_aud"

    // Location audit tables
    const val LOCATION_PRODUCT_AUDIT = "location_product_aud"
    const val PURCHASE_AUDIT = "purchase_aud"
    const val PURCHASE_LINE_AUDIT = "purchase_line_aud"
    const val PURCHASE_DELIVERY_AUDIT = "purchase_delivery_aud"
    const val PURCHASE_DELIVERY_LINE_AUDIT = "purchase_delivery_line_aud"
    const val STOCK_ENTRY_AUDIT = "stock_entry_aud"
    const val STOCK_MOVEMENT_AUDIT = "stock_movement_aud"
    const val SUPPLIER_RETURN_AUDIT = "supplier_return_aud"
}
