package me.ezra_home.retail_software_solution.util.model

object TableNames {
    const val ADDRESS = "address"
    const val SYS_USER = "sys_user"
    const val LOCATION = "location"
    const val CATEGORY = "category"
    const val JOB_TITLE = "job_title"
    const val UNIT_GROUP = "unit_group"
    const val UNIT_VALUE = "unit_value"
    const val ORGANIZATION = "organization"
    const val ORGANIZATION_ADMIN = "organization_admin"
    const val RESERVED_SUBDOMAIN = "reserved_subdomain"
    const val PAYMENT_METHOD = "payment_method"
    const val VARIATION = "variation"
    const val ORGANIZATION_JOIN_REQUEST = "org_join_request"
    const val ORGANIZATION_USER = "organization_user"
    const val PRODUCT = "product"
    const val DB_VERSION = "db_version"
    const val DB_MIGRATION = "db_migration"
    const val TABLE_REGISTRY = "table_registry"
    const val PREFIX_CONFIGURATION = "prefix_configuration"
    const val PREFIX_SEQUENCE_TRACKER = "prefix_sequence_tracker"
    const val ORGANIZATION_PREFIX_SEQUENCE_TRACKER = "organization_prefix_sequence_tracker"
}
