databaseChangeLog:
  - changeSet:
      id: seed-feature-tax-configuration
      author: ezra
      labels: 1.0.0
      changes:
        - insert:
            tableName: feature
            columns:
              - column:
                  name: feature
                  value: TAX_CONFIGURATION
              - column:
                  name: description
                  value: Enables tax configuration; requires at least one org jurisdiction tax type to have account mappings before activation
