package me.ezra_home.retail_software_solution.organizations.business.org_jurisdiction_tax_type

import me.ezra_home.retail_software_solution.organizations.model.OrgJurisdictionTaxTypeEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import java.util.UUID

@Repository
internal interface OrgJurisdictionTaxTypeRepository : JpaRepository<OrgJurisdictionTaxTypeEntity, UUID>
