databaseChangeLog:
  - changeSet:
      id: 'create-unique-index-product-tag-active'
      author: ezra
      labels: 1.0.0
      preConditions:
        - onFail: MARK_RAN
        - not:
            - indexExists:
                indexName: idx_product_tag_active_unique
      changes:
        - sql:
            sql: CREATE UNIQUE INDEX idx_product_tag_active_unique ON product_tag (product_id, tag_id) WHERE end_on IS NULL;
      rollback:
        - dropIndex:
            tableName: product_tag
            indexName: idx_product_tag_active_unique
